'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';

export default function AttemptPage() {
  const [questionPrompt, setQuestionPrompt] = useState('');
  const [answer, setAnswer] = useState('');
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setLoading(true);
    setError(null);

    const response = await fetch('/api/attempt', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ questionPrompt, answer }),
    });

    const data = await response.json();
    if (!response.ok) {
      setError(data.error || 'Unable to evaluate your answer.');
      setLoading(false);
      return;
    }

    setResult(data);
    setLoading(false);
  };

  return (
    <main className="min-h-screen bg-slate-100 px-6 py-20 text-slate-900">
      <div className="container mx-auto max-w-5xl">
        <div className="rounded-[2rem] border border-slate-300 bg-white p-10 shadow-[0_30px_90px_rgba(15,23,42,0.08)]">
          <form onSubmit={submit} className="space-y-10">
            <div className="space-y-4">
              <p className="text-sm uppercase tracking-[0.35em] text-slate-500">Math assessment</p>
              <h1 className="text-4xl font-semibold text-slate-900">Enter your own custom question</h1>
              <p className="max-w-2xl text-base leading-7 text-slate-600">Type any math prompt and submit your answer. The system verifies correctness automatically and saves your attempt.</p>
            </div>

            <div className="rounded-[1.75rem] border border-slate-200 bg-slate-50 p-6 shadow-sm">
              <label className="block text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">Question prompt</label>
              <textarea
                rows={4}
                value={questionPrompt}
                onChange={(event) => setQuestionPrompt(event.target.value)}
                placeholder="e.g., 4+3=?"
                className="mt-4 w-full resize-none rounded-3xl border border-slate-200 bg-white px-5 py-4 text-base text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/10"
                required
              />
            </div>

            <div className="rounded-[1.75rem] border border-slate-200 bg-slate-50 p-6 shadow-sm">
              <label className="block text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">Your answer</label>
              <textarea
                rows={10}
                value={answer}
                onChange={(event) => setAnswer(event.target.value)}
                placeholder="Enter the complete answer and reasoning here..."
                className="mt-4 w-full resize-none rounded-3xl border border-slate-200 bg-white px-5 py-4 text-base text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/10"
                required
              />
            </div>

            {error ? <p className="rounded-3xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p> : null}

            <Button type="submit" className="w-full rounded-3xl bg-brand-600 px-6 py-4 text-lg font-semibold text-white shadow-lg shadow-brand-500/20 transition hover:bg-brand-500" disabled={loading}>
              {loading ? 'Evaluating...' : 'Proceed to Solve'}
            </Button>
          </form>

          {result ? (
            <div className="mt-10 space-y-8 rounded-[1.75rem] border border-slate-200 bg-slate-50 p-6 shadow-sm">
              <div className="flex flex-col gap-4 rounded-[1.75rem] border border-slate-200 bg-white p-6">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Detailed question analysis</p>
                    <h2 className="mt-2 text-2xl font-semibold text-slate-900">Analysis generated by the evaluator</h2>
                  </div>
                  <div className={`rounded-2xl px-4 py-2 text-sm font-semibold ${result.isCorrect ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>
                    {result.isCorrect ? 'Correct' : 'Incorrect'}
                  </div>
                </div>

                <div className="grid gap-4 lg:grid-cols-2">
                  <div className="rounded-3xl bg-slate-50 p-5 border border-slate-200">
                    <p className="text-xs uppercase tracking-[0.25em] text-slate-400">Problem statement</p>
                    <p className="mt-3 text-base leading-7 text-slate-800">{result.prompt}</p>
                  </div>
                  <div className="rounded-3xl bg-slate-50 p-5 border border-slate-200">
                    <p className="text-xs uppercase tracking-[0.25em] text-slate-400">Your answer</p>
                    <p className="mt-3 text-base leading-7 text-slate-800">{answer}</p>
                    <p className={`mt-4 rounded-2xl px-4 py-3 text-sm ${result.isCorrect ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>
                      {result.isCorrect ? 'The answer is correct.' : `Incorrect result. Expected: ${result.correctAnswer}`}
                    </p>
                  </div>
                </div>
              </div>

              <div className="grid gap-6 lg:grid-cols-3">
                <div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm">
                  <h3 className="text-sm uppercase tracking-[0.2em] text-slate-500">Mistakes</h3>
                  <p className="mt-4 text-sm leading-6 text-slate-700">{result.issues.length ? result.issues.join(' ') : 'No major mistakes detected.'}</p>
                </div>
                <div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm">
                  <h3 className="text-sm uppercase tracking-[0.2em] text-slate-500">Missing keywords</h3>
                  <div className="mt-4 flex flex-wrap gap-2">
                    {result.missingKeywords.length ? result.missingKeywords.map((keyword: string) => (
                      <span key={keyword} className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{keyword}</span>
                    )) : <span className="text-sm text-slate-400">None</span>}
                  </div>
                </div>
                <div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm">
                  <h3 className="text-sm uppercase tracking-[0.2em] text-slate-500">Score breakdown</h3>
                  <div className="mt-4 space-y-4">
                    <Progress value={result.matchScore} label="Semantic match" />
                    <Progress value={Math.min(100, result.matchScore + 10)} label="Keyword coverage" />
                  </div>
                </div>
              </div>

              <div className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm">
                <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Solution flow</p>
                <div className="mt-6 grid gap-4 md:grid-cols-5">
                  {result.flow.map((step: string) => (
                    <div key={step} className="rounded-3xl border border-slate-200 bg-slate-50 p-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-700">
                      <p>{step}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </main>
  );
}
